# Step by Step 

Tesnorflow是一个基于numpy的科学计算库，是用来搭建Deep learning模型的工具。

## 环境搭建

在NGC nvidia gpu cloud平台下载tensorflow 2.3的docker image：tensorflow_20.10-tf2-py3.tar.gz

下载完毕后在目录中使用:

```console
gunzip -c tensorflow_20.10-tf2-py3.tar.gz | docker load
```

在vscode中安装python, pylance, remote container插件，打开这个工程, 用ctrl+alt+p打开命令菜单输入container reopen。 这样工作环境搭建完毕。

## 0. 导入tensorflow库

In [1]:
import tensorflow as tf

显示安装tensorflow版本

In [ ]:
print(tf.__version__)

## 1. 创建张量 Tensor

### 一般张量

In [10]:

tf.constant(value=[[1, 2, 3], [3, 4, 5]], dtype=tf.int16)

<tf.Tensor: shape=(2, 3), dtype=int16, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int16)>

### 全为 0

In [ ]:
tf.zeros(shape=[38,38], dtype=tf.int32)

### 全为 1

In [ ]:
tf.ones(shape=[38,38], dtype=tf.int32) # tensor with 38x38 filled with 1

## 随机初始化
适用权重和偏差值的初始化


### 正态分布 random.normal 

In [ ]:
tf.random.normal(shape=[38, 38], mean=0, stddev=1, dtype=tf.float32)

### 正态分布(裁剪) random.truncated_normal  

在使用sigmoid作为激活函数时，在一定程度上可以改善gradient venish（梯度饱和）。



In [ ]:
tf.random.truncated_normal(shape=[38, 38], mean=0, stddev=1, dtype=tf.float32)

### 均匀分布 random.uniform

In [11]:
tf.random.uniform(shape=[3, 3], minval=-1., maxval=1., dtype=tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.7446358 , -0.8749316 , -0.20477581],
       [-0.34861064,  0.03871131, -0.7959955 ],
       [-0.46250916,  0.5117028 , -0.5933111 ]], dtype=float32)>

## 2. 张量的操作

### 打散张量 tf.random.shuffle

In [20]:
index = tf.range(start=0, limit=10, delta=1, dtype=tf.int32)
shuffled = tf.random.shuffle(tf.constant(value=index, dtype=tf.int32))

In [ ]:
tf.reduce_max(shuffled)