# Step by Step 

In [1]:
import tensorflow as tf

## Tensor数据类型





### 全为 0

In [10]:
tf.zeros(shape=[38,38], dtype=tf.int32)



<tf.Tensor: shape=(38, 38), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>

### 全为 1

In [11]:
tf.ones(shape=[38,38], dtype=tf.int32) # tensor with 38x38 filled with 1

<tf.Tensor: shape=(38, 38), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)>

## 随机初始化，适用权重和偏差值的初始化

### random.normal 正态分布


In [12]:
tf.random.normal(shape=[38, 38], mean=0, stddev=1, dtype=tf.float32)

<tf.Tensor: shape=(38, 38), dtype=float32, numpy=
array([[ 0.72260255, -1.5375623 ,  0.648994  , ..., -1.4071993 ,
        -1.326827  , -1.0616107 ],
       [ 0.8225066 ,  0.2567229 , -0.21935514, ...,  0.07383249,
        -0.365342  , -1.1556598 ],
       [-0.8941095 , -0.84467506, -0.01636259, ...,  1.3428128 ,
         0.74234444, -0.4025671 ],
       ...,
       [-0.18138544,  0.8666604 ,  0.733283  , ...,  1.3794061 ,
         1.5378702 , -0.4903225 ],
       [ 1.783662  , -0.22710437, -2.139163  , ..., -0.48147607,
        -1.1879321 ,  0.61631143],
       [-0.2560265 , -0.28852853,  0.21681708, ...,  0.2849576 ,
         1.1807845 ,  0.0094273 ]], dtype=float32)>

### 裁剪正态分布 random.truncated_normal  

可以改善gradient venish（梯度饱和）



In [13]:
tf.random.truncated_normal(shape=[38, 38], mean=0, stddev=1, dtype=tf.float32)

<tf.Tensor: shape=(38, 38), dtype=float32, numpy=
array([[ 0.1358809 , -0.7665587 , -1.7189044 , ...,  0.8445095 ,
        -0.4066623 , -0.28256407],
       [ 0.15385854, -0.4992143 ,  1.0269536 , ...,  1.1694217 ,
         0.99347234,  1.1478807 ],
       [ 0.23131931, -1.318308  ,  0.63011587, ..., -0.09443381,
        -0.7596812 ,  1.4460287 ],
       ...,
       [-1.5437566 , -0.3843725 ,  1.0223138 , ..., -1.6253092 ,
         0.3987385 , -1.3653003 ],
       [ 0.21114609,  0.7819843 , -1.2557315 , ...,  0.93333876,
        -0.24373831,  0.69461817],
       [ 0.11587392, -0.5395601 , -0.23681837, ...,  0.85436493,
         0.18325314,  1.0818373 ]], dtype=float32)>

### 均匀分布: random.uniform 